/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonClear: typeof import('./src/components/nav/ButtonClear.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCountdown: typeof import('element-plus/es')['ElCountdown']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LogoTitle: typeof import('./src/components/nav/LogoTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/nav/SearchBox.vue')['default']
    SearchNavbar: typeof import('./src/components/common/SearchNavbar.vue')['default']
    SliderCaptcha: typeof import('./src/components/canvas/SliderCaptcha.vue')['default']
    SvgIcon: typeof import('./src/components/icon/SvgIcon.vue')['default']
    ThemeToggle: typeof import('./src/components/nav/ThemeToggle.vue')['default']
    ToolCard: typeof import('./src/components/card/ToolCard.vue')['default']
    TopicCard: typeof import('./src/components/card/TopicCard.vue')['default']
    VaultDialog: typeof import('./src/components/common/VaultDialog.vue')['default']
    WordCaptcha: typeof import('./src/components/canvas/WordCaptcha.vue')['default']
  }
}
